
parameters:
  - name: parameter1
    type: string
    default: 'parameter1Value'

variables:
  - name: variable1
    value: 'variable1Value'


# need to output something from a job and use it in the next job

# output something from a stage and use it in another stage



stages:
- stage: Stage1
  jobs:
  - job: Stage1Job1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: steps/get-greeting.yaml
      parameters:
        userName: 'Professor Falken'
    - script: | 

        set -o xtrace
    
        echo 'Parameters are only available at template parse time, not at runtime.'
        echo 'This is the value of parameter1, accessed with the syntax $ {{ parameters.parameter1 }}:'  ${{ parameters.parameter1 }}
        echo 'This is the value of parameter1, accessed with the syntax $ (parameters.parameter1):'  $(parameters.parameter1)

        echo 'Variables available at runtime.'
        echo 'This is the value of variable1 accessed with the template syntax $ {{ variables.variable1 }}': ${{ variables.variable1 }}
        echo 'This is the value of variable1 accessed with the macro syntax $ (variable1)': $(variable1)
 
        echo "Variable from the previous task, accessed with the syntax $ {get_greeting.greeting):" $(get_greeting.greeting)        
        
      displayName: 'Run echo script'
    - template: steps/output-greeting.yaml      
      parameters:
        greeting: $(get_greeting.greeting)

  - job: Stage1Job2
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - script: | 

        set -o xtrace    
      
        echo 'Variables available at runtime.'     
     
        echo "Variable from the task in the previous job, accessed with the syntax $ {get_greeting.greeting):" $(get_greeting.greeting)
        
      displayName: 'Run echo script'
    - template: steps/output-extra-greeting.yaml      
      parameters:
        greeting: $(get_greeting.greeting)
        

# - stage: Stage2
#   jobs:
#   - job: Stage2Job1
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - script: | 

#         set -o xtrace
    
#         echo "Hello, Azure Pipelines!"
#         echo "This is the value of parameter1: ${{ parameters.parameter1 }}"
#       displayName: 'Run echo script'

# - template: ./stages/stage-template.yaml