
parameters:
  - name: parameter1
    type: string
    default: 'default value for parameter1'

stages:
- stage: Stage1
  jobs:
  - job: Job1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: | 
    
        echo "Hello, Azure Pipelines!"
        echo "This is the value of parameter1: ${{ parameters.parameter1 }}"
      displayName: 'Run echo script'