
parameters:
  - name: parameter1
    type: string
    default: 'parameter1Value'

variables:
  - name: variable1
    value: 'variable1Value'

stages:
- stage: Stage1
  jobs:
  - job: Stage1Job1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: | 

        set -o xtrace
    
        echo 'Parameters are only available at template parse time, not at runtime.'
        echo 'This is the value of parameter1, accessed with the syntax $ {{ parameters.parameter1 }}:'  ${{ parameters.parameter1 }}
        echo 'This is the value of parameter1, accessed with the syntax $ (parameters.parameter1):'  $(parameters.parameter1)

        echo 'Variables available at runtime.'
        echo 'This is the value of variable1 accessed with the syntax $ {{ variables.variable1 }}': ${{ variables.variable1 }}
        echo 'This is the value of variable1 accessed with the syntax $ (variable1)': $(variable1)
      displayName: 'Run echo script'

- stage: Stage2
  jobs:
  - job: Stage2Job1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: | 

        set -o xtrace
    
        echo "Hello, Azure Pipelines!"
        echo "This is the value of parameter1: ${{ parameters.parameter1 }}"
      displayName: 'Run echo script'

- template: ./stages/stage-template.yaml